check50:
        # Files available to the checks.
        files: &student_files
                - !include "*"
                - !include ".*" # .env
                - !exclude "node_modules/"

        # Needed Python Packages
        dependencies:
                - beautifulsoup4
                - python-dotenv
                - requests
                - requests_unixsocket
