check50:
        files: &student_files
                - !exclude "*"
                - !include "package.json"
                - !include "package-lock.json"
                - !include "*.js"
                - !include ".env"
                - !exclude "node_modules/"
        dependencies:
                - beautifulsoup4
                - python-dotenv
                - requests
                - requests_unixsocket

submit50:
        files: *student_files
